version: '3'
services:
    web:
        build: .
        links:
            - mongo
        ports:
            - '8000:8080'
    mongo:
        image: 'mongo'
        volumes:
            - ./mongo-volume:/data/db
        ports:
            - '27017:27017'
